- hosts: all
  become: true

  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes

    - name: Install list of packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: Import Docker-CE GPG signing key
      apt_key: url=https://download.docker.com/linux/debian/gpg state=present

    - name: Add Docker-CE repository
      apt_repository:
        repo: 'deb https://download.docker.com/linux/debian {{ansible_distribution_release}} stable'
        state: present

    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: no
        update_cache: yes

    - name: Install Docker-CE
      apt: name=docker-ce state=present

    - name: Run test image
      become: true
      command: docker run hello-world
